name: dext
description: A starting point for Dart libraries or applications.
version: 1.0.0

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  http_parser: ^4.0.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
